- project:
    templates:
      - openstack-cover-jobs
      - check-requirements
      - openstack-lower-constraints-jobs
      - release-notes-jobs-python3
      # NOTE(ianw): 2020-05-29 jobs are unstable; see
      # https://bugs.launchpad.net/tripleo/+bug/1879766
      - tripleo-buildimage-jobs-centos-8
      - openstack-python3-wallaby-jobs
    check:
      jobs:
        - openstack-tox-pylint
        - dib-functests
        - opendev-buildset-registry
        - nodepool-build-image-siblings
        - dib-nodepool-functional-openstack-centos-7-src
        - dib-nodepool-functional-openstack-centos-8-stream-src
        - dib-nodepool-functional-openstack-centos-9-stream-src
        - dib-nodepool-functional-openstack-fedora-35-containerfile-src
        - dib-nodepool-functional-openstack-rockylinux-8-containerfile-src:
            voting: false
        - dib-nodepool-functional-openstack-ubuntu-xenial-src
        - dib-nodepool-functional-openstack-ubuntu-bionic-src
        - dib-nodepool-functional-openstack-ubuntu-focal-src
        - dib-nodepool-functional-openstack-ubuntu-jammy-src
        # NOTE(ianw): 2020-04-22 these have been out of the gate for a
        # while; promote to voting after some stability.
        - dib-nodepool-functional-openstack-opensuse-15-src:
            voting: false
        - dib-nodepool-functional-openstack-opensuse-tumbleweed-src:
            voting: false
        - dib-nodepool-functional-openstack-gentoo-src:
            voting: false
        - dib-nodepool-functional-openstack-debian-bullseye-src:
            voting: false
        - ironic-python-agent-check-image-dib-centos8
        # IPA job that builds AND validates an image via deployment
        - ipa-tempest-bios-ipmi-direct-src:
            voting: false
    check-arm64:
      jobs:
        - dib-functests-arm64-deb
        - dib-functests-arm64-rpm
    gate:
      jobs:
        - openstack-tox-pylint
        - opendev-buildset-registry
        - nodepool-build-image-siblings
        - dib-nodepool-functional-openstack-centos-7-src
        - dib-nodepool-functional-openstack-centos-8-stream-src
        - dib-nodepool-functional-openstack-centos-9-stream-src
        - dib-nodepool-functional-openstack-fedora-35-containerfile-src
        - dib-nodepool-functional-openstack-ubuntu-xenial-src
        - dib-nodepool-functional-openstack-ubuntu-bionic-src
        - dib-nodepool-functional-openstack-ubuntu-focal-src
        - dib-nodepool-functional-openstack-ubuntu-jammy-src
        - dib-functests
        - ironic-python-agent-check-image-dib-centos8
    experimental:
      jobs:
        - opendev-buildset-registry
        - nodepool-build-image-siblings
        - dib-nodepool-functional-openstack-debian-stretch-src
        - dib-nodepool-functional-openstack-debian-buster-src
